# mkdir -p $HOME/.local/bin
# export PATH="$HOME/.local/bin:$PATH"
# source ~/.bashrc
# curl -L https://raw.githubusercontent.com/warrensbox/terraform-switcher/master/install.sh | bash -s -- -b $HOME/.local/bin
# tfswitch --version


git clone https://github.com/tfutils/tfenv.git ~/.tfenv
mkdir ~/bin
ln -s ~/.tfenv/bin/* ~/bin/
